#!/bin/sh
PO="$1"
MO=$(echo "$PO" | sed 's/\.po$/.mo/')
g2lang=$(./generate findg2lang $(basename "$PO" .po))
( cat "$PO"; [ -n "$g2lang" ] && msgunfmt /usr/share/locale/$g2lang/LC_MESSAGES/grub.mo | sed -n '/msgid "[^"]/,$p' ) | msgfmt --no-hash - -o "$MO"
